AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Exampler

Resources:

  Exampler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: exampler.handler
      Runtime: nodejs6.10